[[redirects]]
    from = "/"
    to = "https://seok.tk"
    status = 301!

[[redirects]]
    from = "/index.html"
    to = "https://seok.tk"
    status = 301!

[[redirects]]

    from = "https://photpolio-seok.netlfify.app"
    to = "https://seok.tk"
    status = 301!